config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about", to: "pages#about"
  get "index_open_tasks", to: "tasks#index_open_tasks"
  get "index_closed_tasks", to: "pages#index_closed_tasks"
  get "task/:id", to: "tasks#task"
  get '/oauth2-callback', to: 'oauth#oauth_callback'
  get '/logout', to: 'oauth#logout'
  get '/login', to: 'oauth#login'
  # get "index", to: "pages#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def initialize
    @app_conn = Faraday.new(url: 'https://api-stag.c2.taskrunner.se', headers: { "Content-Type" => "application/x-www-form-urlencoded"})
    # @oauth_client = OAuth2::Client.new(Rails.application.credentials.taskrunner_stag.client_id,
    #                                    Rails.application.credentials.taskrunner_stag.client_secret,
    #                                    site: 'https://api-stag.c2.taskrunner.se',
    #                                    authorize_url: "/oauth/v2/token",
    #                                    token_url: "/oauth/v2/token",
    #                                    redirect_uri: "http://localhost:3000/oauth2-callback",
    #                                    token_method: "post")
    response = Faraday.get('http://httpbingo.org')
    console.log(response)
  end
  # The OAuth callback

  def logout
    # Invalidate session with FusionAuth
    @oauth_client.request(:get, 'oauth2/logout')

    # Reset Rails session
    reset_session

    redirect_to root_path
  end

  def login
    # params = { client_id: Rails.application.credentials.taskrunner_stag.client_id,
    #            client_secret: Rails.application.credentials.taskrunner_stag.client_secret }

    # body = { scope: 'web_poster',
    #          grant_type: 'client_credentials' }
    response = Faraday.get('http://httpbingo.org')
    # encoded_params = URI.encode_www_form(params)
    # encoded_body = URI.encode_www_form(body)
    # response = Faraday.post('https://api-stag.c2.taskrunner.se/oauth/v2/token',
    #                         body: encoded_params,
    #                         headers: { 'Content-Type' => "application/x-www-form-urlencoded" })
    # console.log(response.status)
  end
  # console.log(response.status)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def about
  end

  def index_closed_tasks
  end

  def profile
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index_open_tasks
    @tasks = Task.all
  end

  def task
    @task = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskRunnerOnWeb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/oauth/login.html.erb
<h1>hello christoffer and carli</h1>

app/views/pages/home.html.erb
<div class= "container my-5 text-center">
  <h1><span data-controller="typed-js"></span></h1>

  </div>
    <ul class="results" data-controller="dogs"></ul>
  <div>

  <div class="px-4 ">
    <%= link_to "See your tasks" , index_open_tasks_path, class: "btn btn-primary" %>
  </div>

</div>

app/views/pages/index_closed_tasks.html.erb
<%= link_to "Open tasks", index_open_tasks_path %>
<h1>Closed Tasks</h1>
<div>
  <ul class="list-group">
    <li class="list-group-item">An item</li>
    <li class="list-group-item">A second item</li>
    <li class="list-group-item">A third item</li>
    <li class="list-group-item">A fourth item</li>
    <li class="list-group-item">And a fifth one</li>
  </ul>
</div>

app/views/pages/profile.html.erb
<h2>profile page</h2>

app/views/pages/show.html.erb
<div class="container">
    <h1 class="text-center">Utförd Uppdrag</h1>
  <div class="d-flex justify-content-center">
      <div class="card m-2" style="width: 25rem; border-radius: 15px;">
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class:"d-block w-100"%>
              </div>
              <div class="carousel-item">
                <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class:"d-block w-100"%>
              </div>
              <div class="carousel-item">
                <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class:"d-block w-100"%>
              </div>
            </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
          <div class="card-body">
            <h3>Borra upp tv pa vagg </h3>
            <p class="card-text">Strandvägen 47, 114 56 Stockholm </p>
            <p class="card-text">Bud accepterat </p>
            <p class="card-text">Christoffer Jansson </p>
            <h3>Beskrivning </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
          </div>
      </div>




        <div class="m-2 col-md-8 col-lg-6 col-xl-4">

          <div class="card" id="chat1" style=" width: 25rem; border-radius: 15px;">
            <div
              class="card-header p-3 text-black "
              style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
              <p class="mb-0 fw-bold">Live chat</p>
            </div>
            <div class="card-body">

              <div class="d-flex flex-row justify-content-start mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
                <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
                  <p class="small mb-0">Hi this is supposed to have a yellowish background I working on it..</p>
                </div>
              </div>

              <div class="d-flex flex-row justify-content-end mb-4">
                <div class="p-3 me-3 border" style="border-radius: 15px; background-color: #fbfbfb;">
                  <p class="small mb-0">Thank you, I really like your product.</p>
                </div>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
              </div>

              <div class="d-flex flex-row justify-content-start mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
                <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
                  <p class="small mb-0">Hi this is supposed to have a yellowish background I working on it..</p>
                </div>
              </div>

              <div class="d-flex flex-row justify-content-end mb-4">
                <div class="p-3 me-3 border" style="border-radius: 15px; background-color: #fbfbfb;">
                  <p class="small mb-0">Thank you, I really like your product.</p>
                </div>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
              </div>

              <div class="d-flex flex-row justify-content-start mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
                <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
                  <p class="small mb-0">...</p>
                </div>
              </div>

              <div class="form-outline">
                <textarea class="form-control" id="textAreaExample" rows="4"></textarea>
                <label class="form-label" for="textAreaExample">Type your message</label>
              </div>

            </div>
          </div>

        </div>

  </div>
  <div class="container d-flex justify-content-center">
    <div class="card" style=" width: 30rem; border-radius: 15px;">
      <div class="row ustify-content-center">
        <div class="col-md-4">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">4.9</p>
            <p class="card-text">utförder uppdrag</p>
            <p class="card-text">Verifierad med BankID</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/index_open_tasks.html.erb
<div class="m-5" data-controller="user-phone-number">
  <form action="" id="form" data-action="submit->user-phone-number#phone">
    <input type="number" id="moin" class="form-input" placeholder="Enter the 10 digit mobile">
    <input type="submit">
  </form>
</div>



<%# keep this code it is the list of all the tasks %>
  <div>
    <%= link_to "Closed tasks", index_closed_tasks_path %>
  </div>
  <button class="btn btn-primary btn-lg" data-controller="show_university" data-action="click->show-university#disable">
      Click me!
    </button>
  <h1 class="text-center">Open Tasks</h1>
<div class="container d-flex justify-content-center ">
  <div class="list-group col-sm-4" data-controller="universities" id="tasks" >
  </div>
</div>
  <%= link_to "Back to Homepage", root_path %>

app/views/tasks/task.html.erb
<div class="container">
    <h1 class="text-center">Utförd Uppdrag</h1>
  <div class="d-flex justify-content-center">
      <div class="card m-2" style="width: 25rem; border-radius: 15px;">
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class:"d-block w-100"%>
              </div>
              <div class="carousel-item">
                <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class:"d-block w-100"%>
              </div>
              <div class="carousel-item">
                <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class:"d-block w-100"%>
              </div>
            </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
          <div class="card-body">
            <h3>Borra upp tv pa vagg </h3>
            <p class="card-text">Strandvägen 47, 114 56 Stockholm </p>
            <p class="card-text">Bud accepterat </p>
            <p class="card-text">Christoffer Jansson </p>
            <h3>Beskrivning </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
          </div>
      </div>




        <div class="m-2 col-md-8 col-lg-6 col-xl-4">

          <div class="card" id="chat1" style=" width: 25rem; border-radius: 15px;">
            <div
              class="card-header p-3 text-black "
              style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
              <p class="mb-0 fw-bold">Live chat</p>
            </div>
            <div class="card-body">

              <div class="d-flex flex-row justify-content-start mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
                <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
                  <p class="small mb-0">Hi this is supposed to have a yellowish background I working on it..</p>
                </div>
              </div>

              <div class="d-flex flex-row justify-content-end mb-4">
                <div class="p-3 me-3 border" style="border-radius: 15px; background-color: #fbfbfb;">
                  <p class="small mb-0">Thank you, I really like your product.</p>
                </div>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
              </div>

              <div class="d-flex flex-row justify-content-start mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
                <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
                  <p class="small mb-0">Hi this is supposed to have a yellowish background I working on it..</p>
                </div>
              </div>

              <div class="d-flex flex-row justify-content-end mb-4">
                <div class="p-3 me-3 border" style="border-radius: 15px; background-color: #fbfbfb;">
                  <p class="small mb-0">Thank you, I really like your product.</p>
                </div>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
              </div>

              <div class="d-flex flex-row justify-content-start mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="avatar 1" style="width: 45px; height: 100%;">
                <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
                  <p class="small mb-0">...</p>
                </div>
              </div>

              <div class="form-outline">
                <textarea class="form-control" id="textAreaExample" rows="4"></textarea>
                <label class="form-label" for="textAreaExample">Type your message</label>
              </div>

            </div>
          </div>

        </div>

  </div>
  <div class="container d-flex justify-content-center">
    <div class="card" style=" width: 30rem; border-radius: 15px;">
      <div class="row ustify-content-center">
        <div class="col-md-4">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">4.9</p>
            <p class="card-text">utförder uppdrag</p>
            <p class="card-text">Verifierad med BankID</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>